using DesignPatternCodeGenerator.Base.Generators;
using DesignPatternCodeGenerator.Base.Models;
using DesignPatternCodeGenerator.Factory;
using DesignPatternCodeGenerator.Singleton;
using DesignPatternCodeGenerator.Tests.Helpers;
using FluentAssertions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xunit;

namespace DesignPatternCodeGenerator.Tests.Singleton;

public class SingletonContentGeneratorTests
{
    [Theory]
    [InlineData(SINGLETON_COMPILATION_SOURCE, EXPECTED_COMPILATION_SOURCE)]
    internal void GenerateClass_ForValidInputs_ReturnInterface(string inputSource, string expectedSource)
    {
        var codeGenerator = new BaseCodeGenerator(_syntaxTokens, _configuration);
        var classGroup = GeneratorTestsHelper.GetClassGroup(inputSource);

        var result = SingletonContentGenerator.GenerateClass(codeGenerator, classGroup);

        result.RemoveWhitespace()
            .Should()
            .Be(expectedSource.RemoveWhitespace());

    }

    private readonly SyntaxTokensConfigurations _configuration = new()
    {
        IsPartialClass = true,
    };

    private readonly SyntaxTokens _syntaxTokens = new()
    {
        ClassName = "Test",
        InterfaceName = "ITest",
        Namespace = "Test.Test",
        Accessibility = "public",
        Usings = new List<string>() { "System" },
        AdditionalClassToken = " partial"
    };

    private const string SINGLETON_COMPILATION_SOURCE =
    @"using DesignPatternCodeGenerator.Attributes.Singleton;
using System;

namespace Test.Test
{
    [Singleton]
    public partial class Test
    {

    }
}";

    private const string EXPECTED_COMPILATION_SOURCE =
@"// <auto-generated/>
using System;

namespace Test.Test
{
    public partial class Test
    {
        private static Test _instance = null;
        private static object obj = new object();

        private Test() { }

        public static Test GetInstance()
        {
            lock(obj)
            {
                if (_instance == null)
                {
                    _instance = new Test();
                }
            }
            return _instance;
        }        
    }
}";
}
