using DesignPatternCodeGenerator.Factory;
using DesignPatternCodeGenerator.Tests.Helpers;
using FluentAssertions;
using Xunit;

namespace DesignPatternCodeGenerator.Tests.Factory;

public class FactoryContentGeneratorTests
{
    [Theory]
    [InlineData(FACTORY_COMPILATION_SOURCE, INTERFACE_FACTORY_SOURCE)]
    internal void GenerateInterface_ForValidInputs_ReturnInterface(string inputSource, string interfaceSource)
    {
        var interfaceGroup = GeneratorTestsHelper.GetInterfaceGroup(inputSource);

        var result = FactoryContentGenerator.GenerateInterface(interfaceGroup);

        result.RemoveWhitespace().Should().Be(interfaceSource.RemoveWhitespace());
    }

    [Theory]
    [InlineData(FACTORY_COMPILATION_SOURCE, CLASS_FACTORY_SOURCE, FACTORYCHILD_COMPILATION_SOURCE)]
    internal void GenerateClass_ForValidInputs_ReturnInterface(string inputSource, string classSource, string childSource)
    {
        var interfaceGroup = GeneratorTestsHelper.GetInterfaceGroup(inputSource);
        var childGroups = GeneratorTestsHelper.GetClassGroups(childSource);

        var result = FactoryContentGenerator.GenerateClass(interfaceGroup, childGroups);

        result.RemoveWhitespace().Should().Be(classSource.RemoveWhitespace());
    }

    private const string FACTORY_COMPILATION_SOURCE =
    @"using DesignPatternCodeGenerator.Attributes.Factory;
using System;

namespace Test.Test
{

    [Factory]
    public interface ITest
    {

    }

    [FactoryProduct]
    public class Test : ITest
    {

    }
}";

    private const string INTERFACE_FACTORY_SOURCE =
    @"// <auto-generated/>
using DesignPatternCodeGenerator.Attributes.Factory;
using System;

namespace Test.Test
{
    public interface ITestFactory
    {
        public ITest Create(TestFactoryType type);
    }
}";

    private const string FACTORYCHILD_COMPILATION_SOURCE =
    @"using DesignPatternCodeGenerator.Attributes.Factory;
using System;

namespace Test.Test
{
    [Factory]
    public interface ITest { }

    [FactoryProduct]
    public class Test1 : ITest { }

    [FactoryProduct]
    public class Test2 : ITest { }

    [FactoryProduct]
    public class Test3 : ITest { }
}";

    private const string CLASS_FACTORY_SOURCE =
    @"// <auto-generated/>
using DesignPatternCodeGenerator.Attributes.Factory;
using System;

namespace Test.Test
{
    public class TestFactory: ITestFactory
    {
	    

		public TestFactory()
        {
	        
        }

	    public ITest Create(TestFactoryType type)
        {
            switch (type)
            {
                case TestFactoryType.Test1 :
					return new Test1();
				case TestFactoryType.Test2 :
					return new Test2();
				case TestFactoryType.Test3 :
					return new Test3();
                default :
                    throw new Exception($""Type { type } is not handled"");
            }    
        }

    }
}";
}
